// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trAInr.API.Data;

#nullable disable

namespace trAInr.API.Migrations
{
    [DbContext(typeof(TrainrDbContext))]
    partial class TrainrDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("trAInr.API.Models.Domain.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSystemExercise")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryMuscleGroup");

                    b.HasIndex("Type");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Barbell bench press for chest development",
                            IsSystemExercise = true,
                            Name = "Bench Press",
                            PrimaryMuscleGroup = 1,
                            SecondaryMuscleGroup = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Incline press targeting upper chest",
                            IsSystemExercise = true,
                            Name = "Incline Dumbbell Press",
                            PrimaryMuscleGroup = 1,
                            SecondaryMuscleGroup = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cable chest fly for isolation",
                            IsSystemExercise = true,
                            Name = "Cable Fly",
                            PrimaryMuscleGroup = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bodyweight chest exercise",
                            IsSystemExercise = true,
                            Name = "Push-ups",
                            PrimaryMuscleGroup = 1,
                            SecondaryMuscleGroup = 5,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111201"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Conventional deadlift for overall back development",
                            IsSystemExercise = true,
                            Name = "Deadlift",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111202"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bodyweight back exercise",
                            IsSystemExercise = true,
                            Name = "Pull-ups",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111203"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bent-over barbell row",
                            IsSystemExercise = true,
                            Name = "Barbell Row",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111204"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cable lat pulldown",
                            IsSystemExercise = true,
                            Name = "Lat Pulldown",
                            PrimaryMuscleGroup = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111301"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standing barbell overhead press",
                            IsSystemExercise = true,
                            Name = "Overhead Press",
                            PrimaryMuscleGroup = 3,
                            SecondaryMuscleGroup = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111302"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dumbbell lateral raise",
                            IsSystemExercise = true,
                            Name = "Lateral Raise",
                            PrimaryMuscleGroup = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111303"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cable face pull for rear delts",
                            IsSystemExercise = true,
                            Name = "Face Pull",
                            PrimaryMuscleGroup = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111401"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standing barbell bicep curl",
                            IsSystemExercise = true,
                            Name = "Barbell Curl",
                            PrimaryMuscleGroup = 4,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111402"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cable tricep pushdown",
                            IsSystemExercise = true,
                            Name = "Tricep Pushdown",
                            PrimaryMuscleGroup = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111403"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dumbbell hammer curl",
                            IsSystemExercise = true,
                            Name = "Hammer Curl",
                            PrimaryMuscleGroup = 4,
                            SecondaryMuscleGroup = 6,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111404"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lying tricep extension",
                            IsSystemExercise = true,
                            Name = "Skull Crushers",
                            PrimaryMuscleGroup = 5,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111501"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Back squat for leg development",
                            IsSystemExercise = true,
                            Name = "Barbell Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111502"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RDL for hamstring development",
                            IsSystemExercise = true,
                            Name = "Romanian Deadlift",
                            PrimaryMuscleGroup = 9,
                            SecondaryMuscleGroup = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111503"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Machine leg press",
                            IsSystemExercise = true,
                            Name = "Leg Press",
                            PrimaryMuscleGroup = 8,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111504"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lying leg curl",
                            IsSystemExercise = true,
                            Name = "Leg Curl",
                            PrimaryMuscleGroup = 9,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111505"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standing calf raise",
                            IsSystemExercise = true,
                            Name = "Calf Raise",
                            PrimaryMuscleGroup = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111506"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Walking or stationary lunges",
                            IsSystemExercise = true,
                            Name = "Lunges",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111601"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Isometric core exercise",
                            IsSystemExercise = true,
                            Name = "Plank",
                            PrimaryMuscleGroup = 7,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111602"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Weighted cable crunch",
                            IsSystemExercise = true,
                            Name = "Cable Crunch",
                            PrimaryMuscleGroup = 7,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111603"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Core exercise for lower abs",
                            IsSystemExercise = true,
                            Name = "Hanging Leg Raise",
                            PrimaryMuscleGroup = 7,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111701"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Outdoor or treadmill running",
                            IsSystemExercise = true,
                            Name = "Running",
                            PrimaryMuscleGroup = 13,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111702"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stationary or outdoor cycling",
                            IsSystemExercise = true,
                            Name = "Cycling",
                            PrimaryMuscleGroup = 13,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111703"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Rowing machine",
                            IsSystemExercise = true,
                            Name = "Rowing",
                            PrimaryMuscleGroup = 13,
                            SecondaryMuscleGroup = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111704"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Swimming laps",
                            IsSystemExercise = true,
                            Name = "Swimming",
                            PrimaryMuscleGroup = 12,
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111705"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Skipping rope for cardio",
                            IsSystemExercise = true,
                            Name = "Jump Rope",
                            PrimaryMuscleGroup = 13,
                            Type = 2
                        });
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Intensity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.Programme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreMade")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("UserId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.ProgrammeWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProgrammeId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("ProgrammeWeeks");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FitnessLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PrimaryGoal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkoutDaysPerWeek")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProgrammeWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeWeekId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId", "OrderIndex");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.ExerciseSet", b =>
                {
                    b.HasOne("trAInr.API.Models.Domain.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.Programme", b =>
                {
                    b.HasOne("trAInr.API.Models.Domain.User", "User")
                        .WithMany("Programmes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.ProgrammeWeek", b =>
                {
                    b.HasOne("trAInr.API.Models.Domain.Programme", "Programme")
                        .WithMany("Weeks")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutDay", b =>
                {
                    b.HasOne("trAInr.API.Models.Domain.ProgrammeWeek", "ProgrammeWeek")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("ProgrammeWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeWeek");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutExercise", b =>
                {
                    b.HasOne("trAInr.API.Models.Domain.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trAInr.API.Models.Domain.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.Exercise", b =>
                {
                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.Programme", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.ProgrammeWeek", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.User", b =>
                {
                    b.Navigation("Programmes");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("trAInr.API.Models.Domain.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
