// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trAInr.Infrastructure.Data;

#nullable disable

namespace trAInr.Infrastructure.Migrations
{
    [DbContext(typeof(TrainrDbContext))]
    [Migration("20260103231932_AddSupersetAndDropSetFeatures")]
    partial class AddSupersetAndDropSetFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("trAInr.Domain.Aggregates.AssignedProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgramTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("IsActive");

                    b.ToTable("AssignedPrograms");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PrimaryGoal")
                        .HasColumnType("integer");

                    b.Property<string>("ReadinessNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("ReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkoutDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("_constraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_equipmentPreferences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EquipmentPreferences");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.ExerciseDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSystemExercise")
                        .HasColumnType("boolean");

                    b.Property<int>("MovementPattern")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("_equipmentRequirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EquipmentRequirements");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryMuscleGroup");

                    b.HasIndex("Type");

                    b.ToTable("ExerciseDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A compound exercise targeting the chest, shoulders, and triceps. Lie on a bench and press a barbell upward from your chest.",
                            Instructions = "Lie flat on bench, grip bar slightly wider than shoulders. Lower bar to chest, then press up explosively.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Bench Press",
                            PrimaryMuscleGroup = 1,
                            SecondaryMuscleGroup = 5,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A bodyweight exercise that strengthens the chest, shoulders, and triceps. No equipment needed.",
                            Instructions = "Start in plank position, lower body until chest nearly touches floor, push back up.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Push-ups",
                            PrimaryMuscleGroup = 1,
                            SecondaryMuscleGroup = 5,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A vertical pressing movement that primarily targets the shoulders and triceps.",
                            Instructions = "Stand with feet shoulder-width apart, press barbell or dumbbells overhead from shoulder height.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Overhead Press",
                            PrimaryMuscleGroup = 3,
                            SecondaryMuscleGroup = 5,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A bodyweight exercise targeting triceps, chest, and shoulders. Performed on parallel bars or bench.",
                            Instructions = "Support body on parallel bars, lower until elbows are at 90 degrees, push back up.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Dips",
                            PrimaryMuscleGroup = 5,
                            SecondaryMuscleGroup = 1,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An isolation exercise that targets the chest muscles through a wide arc of motion.",
                            Instructions = "Lie on bench, hold dumbbells with arms slightly bent. Lower weights in wide arc, bring together above chest.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Dumbbell Flyes",
                            PrimaryMuscleGroup = 1,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A bodyweight exercise that targets the back and biceps. One of the best upper body exercises.",
                            Instructions = "Hang from bar with palms facing away, pull body up until chin clears bar, lower with control.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Pull-ups",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A compound pulling exercise that targets the back, biceps, and rear deltoids.",
                            Instructions = "Bend at hips, keep back straight, pull barbell to lower chest/upper abdomen, squeeze back muscles.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Barbell Rows",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A machine exercise that targets the latissimus dorsi and biceps.",
                            Instructions = "Sit at lat pulldown machine, pull bar to upper chest, control the weight on the way up.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Lat Pulldown",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A rear deltoid and upper back exercise performed with a cable machine.",
                            Instructions = "Set cable at face height, pull rope to face level, separate handles at end, squeeze rear delts.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Face Pulls",
                            PrimaryMuscleGroup = 3,
                            SecondaryMuscleGroup = 2,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A compound exercise targeting the middle and upper back, biceps, and rear deltoids.",
                            Instructions = "Bend forward at hips, keep back straight, pull dumbbells or barbell to lower chest/upper abdomen.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Bent-Over Rows",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 4,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The king of leg exercises. A compound movement targeting quadriceps, glutes, and core.",
                            Instructions = "Bar on upper back, feet shoulder-width apart, squat down until thighs parallel to floor, drive up through heels.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Back Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A squat variation with the bar in front, emphasizing quadriceps and core strength.",
                            Instructions = "Bar across front deltoids, elbows up, squat down keeping torso upright, drive up through midfoot.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Front Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 7,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A beginner-friendly squat variation using a single dumbbell or kettlebell.",
                            Instructions = "Hold weight at chest, squat down keeping torso upright, drive up through heels.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Goblet Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333334"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fundamental bodyweight exercise for lower body strength. No equipment needed.",
                            Instructions = "Feet shoulder-width apart, squat down until thighs parallel to floor, drive up through heels.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Bodyweight Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333335"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A plyometric variation of the squat that adds explosive power and cardiovascular benefits.",
                            Instructions = "Perform a squat, then explosively jump up, land softly and immediately go into next squat.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Jump Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The ultimate posterior chain exercise. Targets hamstrings, glutes, and entire back.",
                            Instructions = "Feet hip-width apart, bar over midfoot, hinge at hips, keep back straight, drive hips forward to stand.",
                            IsSystemExercise = true,
                            MovementPattern = 4,
                            Name = "Deadlift",
                            PrimaryMuscleGroup = 9,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A deadlift variation emphasizing hamstring and glute stretch and strength.",
                            Instructions = "Start standing, hinge at hips keeping legs relatively straight, lower bar along legs, feel hamstring stretch, return.",
                            IsSystemExercise = true,
                            MovementPattern = 4,
                            Name = "Romanian Deadlift",
                            PrimaryMuscleGroup = 9,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444443"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A posterior chain exercise performed with a barbell on the upper back.",
                            Instructions = "Bar on upper back, hinge at hips keeping back straight, lower torso until parallel to floor, return.",
                            IsSystemExercise = true,
                            MovementPattern = 4,
                            Name = "Good Mornings",
                            PrimaryMuscleGroup = 9,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An exercise that directly targets the glutes through hip extension.",
                            Instructions = "Upper back on bench, bar across hips, drive hips up squeezing glutes, lower with control.",
                            IsSystemExercise = true,
                            MovementPattern = 4,
                            Name = "Hip Thrust",
                            PrimaryMuscleGroup = 10,
                            SecondaryMuscleGroup = 9,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444445"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dynamic hip hinge movement that builds power and endurance in the posterior chain.",
                            Instructions = "Hinge at hips, swing kettlebell from between legs to chest height using hip drive, not arms.",
                            IsSystemExercise = true,
                            MovementPattern = 4,
                            Name = "Kettlebell Swing",
                            PrimaryMuscleGroup = 10,
                            SecondaryMuscleGroup = 9,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dynamic unilateral leg exercise that improves balance and leg strength.",
                            Instructions = "Step forward into lunge position, both knees at 90 degrees, push off front foot to step forward with other leg.",
                            IsSystemExercise = true,
                            MovementPattern = 5,
                            Name = "Walking Lunges",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A lunge variation that reduces knee stress while targeting quadriceps and glutes.",
                            Instructions = "Step backward into lunge, front knee at 90 degrees, push through front heel to return to start.",
                            IsSystemExercise = true,
                            MovementPattern = 5,
                            Name = "Reverse Lunges",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555553"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An intense unilateral leg exercise performed with rear foot elevated.",
                            Instructions = "Rear foot on bench, front leg does the work, squat down until front thigh parallel, drive up.",
                            IsSystemExercise = true,
                            MovementPattern = 5,
                            Name = "Bulgarian Split Squat",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555554"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A side-to-side lunge variation that targets the inner thighs and glutes.",
                            Instructions = "Step to the side, shift weight to that leg, squat down keeping other leg straight, return to center.",
                            IsSystemExercise = true,
                            MovementPattern = 5,
                            Name = "Lateral Lunges",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A classic lunge variation stepping forward to target quadriceps and glutes.",
                            Instructions = "Step forward into lunge, both knees at 90 degrees, push through front heel to return to start.",
                            IsSystemExercise = true,
                            MovementPattern = 5,
                            Name = "Forward Lunges",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A full-body strength and conditioning exercise. Carry heavy weights while walking.",
                            Instructions = "Pick up heavy weights (dumbbells, kettlebells, or farmer's walk handles), walk for distance or time, keep core tight.",
                            IsSystemExercise = true,
                            MovementPattern = 6,
                            Name = "Farmer's Walk",
                            PrimaryMuscleGroup = 12,
                            SecondaryMuscleGroup = 7,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A unilateral carry that challenges core stability and grip strength.",
                            Instructions = "Carry a single heavy weight at your side, walk while resisting lateral flexion, switch sides.",
                            IsSystemExercise = true,
                            MovementPattern = 6,
                            Name = "Suitcase Carry",
                            PrimaryMuscleGroup = 7,
                            SecondaryMuscleGroup = 12,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666663"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A carry variation with weight held overhead, challenging shoulder stability and core.",
                            Instructions = "Press weight overhead, walk while maintaining overhead position, keep core engaged.",
                            IsSystemExercise = true,
                            MovementPattern = 6,
                            Name = "Overhead Carry",
                            PrimaryMuscleGroup = 3,
                            SecondaryMuscleGroup = 7,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666664"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Carrying weight in the front rack position, challenging core and upper body.",
                            Instructions = "Hold weight(s) at shoulder height in front rack position, walk maintaining position.",
                            IsSystemExercise = true,
                            MovementPattern = 6,
                            Name = "Rack Carry",
                            PrimaryMuscleGroup = 7,
                            SecondaryMuscleGroup = 12,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fundamental core strengthening exercise performed in a static position.",
                            Instructions = "Hold body in straight line on forearms and toes, keep core tight, don't let hips sag or rise.",
                            IsSystemExercise = true,
                            MovementPattern = 7,
                            Name = "Plank",
                            PrimaryMuscleGroup = 7,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An isometric leg exercise that builds quadriceps and glute endurance.",
                            Instructions = "Back against wall, slide down until thighs parallel to floor, hold position, keep back flat against wall.",
                            IsSystemExercise = true,
                            MovementPattern = 7,
                            Name = "Wall Sit",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 10,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777773"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An advanced core exercise that targets the entire anterior core chain.",
                            Instructions = "Lie on back, lift shoulders and legs off ground, maintain banana shape, keep lower back pressed to floor.",
                            IsSystemExercise = true,
                            MovementPattern = 7,
                            Name = "Hollow Body Hold",
                            PrimaryMuscleGroup = 7,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777774"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An advanced isometric exercise that challenges core, hip flexors, and triceps.",
                            Instructions = "Support body on parallel bars or floor, lift legs to form L-shape, hold position.",
                            IsSystemExercise = true,
                            MovementPattern = 7,
                            Name = "L-Sit",
                            PrimaryMuscleGroup = 7,
                            SecondaryMuscleGroup = 5,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777775"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An isometric exercise that improves grip strength and shoulder mobility.",
                            Instructions = "Hang from pull-up bar with straight arms, hold position, focus on grip and shoulder engagement.",
                            IsSystemExercise = true,
                            MovementPattern = 7,
                            Name = "Dead Hang",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 6,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A fundamental cardiovascular exercise that improves endurance and cardiovascular health.",
                            Instructions = "Maintain steady pace, land on midfoot, keep posture upright, breathe rhythmically.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Running",
                            PrimaryMuscleGroup = 13,
                            SecondaryMuscleGroup = 12,
                            Type = 2,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A low-impact cardiovascular exercise that targets the legs and improves endurance.",
                            Instructions = "Maintain consistent cadence, adjust resistance for intensity, keep core engaged.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Cycling",
                            PrimaryMuscleGroup = 8,
                            SecondaryMuscleGroup = 13,
                            Type = 2,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888883"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A full-body cardiovascular exercise that targets legs, back, and core.",
                            Instructions = "Drive with legs, lean back slightly, pull handle to chest, return with control.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Rowing",
                            PrimaryMuscleGroup = 12,
                            SecondaryMuscleGroup = 13,
                            Type = 2,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888884"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A high-intensity full-body exercise combining squat, push-up, and jump.",
                            Instructions = "Squat down, jump feet back to plank, do push-up, jump feet forward, jump up with arms overhead.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Burpees",
                            PrimaryMuscleGroup = 12,
                            SecondaryMuscleGroup = 13,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888885"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A high-intensity cardiovascular exercise that improves coordination and endurance.",
                            Instructions = "Keep elbows close, jump on balls of feet, maintain rhythm, start slow and build speed.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Jump Rope",
                            PrimaryMuscleGroup = 13,
                            SecondaryMuscleGroup = 11,
                            Type = 2,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A stretching exercise that improves hip flexibility and reduces lower back tension.",
                            Instructions = "Kneel on one knee, other foot forward, push hips forward until stretch felt in front of hip, hold 30-60 seconds.",
                            IsSystemExercise = true,
                            MovementPattern = 9,
                            Name = "Hip Flexor Stretch",
                            PrimaryMuscleGroup = 7,
                            Type = 4,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A flexibility exercise targeting the hamstring muscles.",
                            Instructions = "Sit or stand, extend one leg, lean forward until stretch felt in back of thigh, hold 30-60 seconds.",
                            IsSystemExercise = true,
                            MovementPattern = 9,
                            Name = "Hamstring Stretch",
                            PrimaryMuscleGroup = 9,
                            Type = 4,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999993"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A mobility exercise that improves shoulder range of motion and flexibility.",
                            Instructions = "Perform arm circles, cross-body stretches, and wall slides to improve shoulder mobility.",
                            IsSystemExercise = true,
                            MovementPattern = 9,
                            Name = "Shoulder Mobility",
                            PrimaryMuscleGroup = 3,
                            Type = 4,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999994"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A spinal mobility exercise that improves flexibility in the back and core.",
                            Instructions = "Start on hands and knees, arch back (cow), then round back (cat), move slowly between positions.",
                            IsSystemExercise = true,
                            MovementPattern = 9,
                            Name = "Cat-Cow Stretch",
                            PrimaryMuscleGroup = 7,
                            SecondaryMuscleGroup = 2,
                            Type = 4,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999995"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A yoga-inspired stretch that targets the hip flexors and glutes.",
                            Instructions = "From plank, bring one knee forward to same-side wrist, extend other leg back, hold and breathe.",
                            IsSystemExercise = true,
                            MovementPattern = 9,
                            Name = "Pigeon Pose",
                            PrimaryMuscleGroup = 10,
                            SecondaryMuscleGroup = 7,
                            Type = 4,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A full-body exercise combining front squat and overhead press in one movement.",
                            Instructions = "Hold weight at shoulder height, squat down, drive up explosively and press weight overhead.",
                            IsSystemExercise = true,
                            MovementPattern = 3,
                            Name = "Thruster",
                            PrimaryMuscleGroup = 12,
                            SecondaryMuscleGroup = 3,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaab"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A complex full-body movement that improves stability, strength, and coordination.",
                            Instructions = "Lie on back holding weight overhead, get up to standing position through series of movements, reverse to return.",
                            IsSystemExercise = true,
                            MovementPattern = 6,
                            Name = "Turkish Get-Up",
                            PrimaryMuscleGroup = 12,
                            SecondaryMuscleGroup = 7,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaac"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A compound exercise combining plank and rowing motion for core and back.",
                            Instructions = "In plank position with dumbbells, row one weight to side while maintaining plank, alternate sides.",
                            IsSystemExercise = true,
                            MovementPattern = 2,
                            Name = "Renegade Row",
                            PrimaryMuscleGroup = 2,
                            SecondaryMuscleGroup = 7,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A dynamic core and cardio exercise performed in plank position.",
                            Instructions = "In plank position, alternate bringing knees to chest rapidly, keep core engaged throughout.",
                            IsSystemExercise = true,
                            MovementPattern = 8,
                            Name = "Mountain Climbers",
                            PrimaryMuscleGroup = 7,
                            SecondaryMuscleGroup = 13,
                            Type = 3,
                            _equipmentRequirements = "[]"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaae"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An isolation exercise targeting the calf muscles.",
                            Instructions = "Stand on balls of feet, raise up onto toes, lower with control, can add weight for resistance.",
                            IsSystemExercise = true,
                            MovementPattern = 1,
                            Name = "Calf Raises",
                            PrimaryMuscleGroup = 11,
                            Type = 1,
                            _equipmentRequirements = "[]"
                        });
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProgrammeWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("ProgrammeWeekId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSystemExercise")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("DropPercentage")
                        .HasColumnType("numeric");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Intensity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SetType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedProgramId");

                    b.HasIndex("AssignedProgramId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("ProgrammeWeeks");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgrammeWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeWeekId");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciseDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersetGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SupersetRestSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.WorkoutSession", b =>
                {
                    b.OwnsMany("trAInr.Domain.Aggregates.ExerciseInstance", "ExerciseInstances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("ExerciseDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExerciseName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("TargetDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<int?>("TargetDurationSeconds")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetReps")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetSets")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("TargetWeight")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<Guid>("WorkoutSessionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutSessionId");

                            b1.ToTable("ExerciseInstances", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutSessionId");

                            b1.OwnsMany("trAInr.Domain.Aggregates.CompletedSet", "CompletedSets", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("CompletedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<decimal?>("Distance")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)");

                                    b2.Property<int?>("DurationSeconds")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ExerciseInstanceId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("IsCompleted")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsWarmup")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<int?>("RPE")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SetNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal?>("Weight")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExerciseInstanceId");

                                    b2.ToTable("CompletedSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExerciseInstanceId");
                                });

                            b1.Navigation("CompletedSets");
                        });

                    b.Navigation("ExerciseInstances");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ExerciseSet", b =>
                {
                    b.HasOne("trAInr.Domain.Entities.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.AssignedProgram", "AssignedProgram")
                        .WithMany("Weeks")
                        .HasForeignKey("AssignedProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedProgram");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.HasOne("trAInr.Domain.Entities.ProgrammeWeek", "ProgrammeWeek")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("ProgrammeWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeWeek");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.ExerciseDefinition", "ExerciseDefinition")
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trAInr.Domain.Entities.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDefinition");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.AssignedProgram", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
