// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using trAInr.Infrastructure.Data;

#nullable disable

namespace trAInr.Infrastructure.Migrations
{
    [DbContext(typeof(TrainrDbContext))]
    [Migration("20260125112453_ChangeExerciseDefinitionIdToInt")]
    partial class ChangeExerciseDefinitionIdToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("trAInr.Domain.Aggregates.AssignedProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgramTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("IsActive");

                    b.ToTable("AssignedPrograms");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("PrimaryGoal")
                        .HasColumnType("integer");

                    b.Property<string>("ReadinessNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("ReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkoutDaysPerWeek")
                        .HasColumnType("integer");

                    b.Property<string>("_constraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("_equipmentPreferences")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EquipmentPreferences");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.ExerciseDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSystemExercise")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelOfDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("MovementPattern")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("_equipmentRequirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EquipmentRequirements");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryMuscleGroup");

                    b.HasIndex("Type");

                    b.ToTable("ExerciseDefinitions");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.ProgramTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienceLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceLevel");

                    b.HasIndex("Name");

                    b.ToTable("ProgramTemplates");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProgrammeWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("ProgrammeWeekId");

                    b.HasIndex("ScheduledDate");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSystemExercise")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PrimaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryMuscleGroup")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ExerciseSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Distance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("DropPercentage")
                        .HasColumnType("numeric");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int?>("Intensity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SetType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutExerciseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutExerciseId");

                    b.ToTable("ExerciseSets");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProgramTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProgramTemplateId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("ProgramTemplateWeeks");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProgramTemplateWeekId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProgramTemplateWeekId");

                    b.ToTable("ProgramTemplateWorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProgramTemplateWorkoutDayId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersetGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SupersetRestSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDistance")
                        .HasColumnType("numeric");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("ProgramTemplateWorkoutDayId");

                    b.ToTable("ProgramTemplateWorkoutExercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedProgramId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("WeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssignedProgramId");

                    b.HasIndex("AssignedProgramId", "WeekNumber")
                        .IsUnique();

                    b.ToTable("ProgrammeWeeks");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestDay")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgrammeWeekId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProgrammeWeekId");

                    b.ToTable("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExerciseDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("RestSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SupersetGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SupersetRestSeconds")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetDistance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("TargetDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetRpe")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("WorkoutDayId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseDefinitionId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("WorkoutExercises");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.WorkoutSession", b =>
                {
                    b.OwnsMany("trAInr.Domain.Aggregates.ExerciseInstance", "ExerciseInstances", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("ExerciseDefinitionId")
                                .HasColumnType("integer");

                            b1.Property<string>("ExerciseName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Notes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("OrderIndex")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("TargetDistance")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<int?>("TargetDurationSeconds")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetReps")
                                .HasColumnType("integer");

                            b1.Property<int>("TargetSets")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("TargetWeight")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)");

                            b1.Property<Guid>("WorkoutSessionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkoutSessionId");

                            b1.ToTable("ExerciseInstances", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutSessionId");

                            b1.OwnsMany("trAInr.Domain.Aggregates.CompletedSet", "CompletedSets", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("CompletedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("CreatedAt")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<decimal?>("Distance")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)");

                                    b2.Property<int?>("DurationSeconds")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ExerciseInstanceId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("IsCompleted")
                                        .HasColumnType("boolean");

                                    b2.Property<bool>("IsWarmup")
                                        .HasColumnType("boolean");

                                    b2.Property<string>("Notes")
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)");

                                    b2.Property<int?>("RPE")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SetNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal?>("Weight")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ExerciseInstanceId");

                                    b2.ToTable("CompletedSets", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ExerciseInstanceId");
                                });

                            b1.Navigation("CompletedSets");
                        });

                    b.Navigation("ExerciseInstances");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ExerciseSet", b =>
                {
                    b.HasOne("trAInr.Domain.Entities.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Sets")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWeek", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.ProgramTemplate", "ProgramTemplate")
                        .WithMany("Weeks")
                        .HasForeignKey("ProgramTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramTemplate");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWorkoutDay", b =>
                {
                    b.HasOne("trAInr.Domain.Entities.ProgramTemplateWeek", "ProgramTemplateWeek")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("ProgramTemplateWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramTemplateWeek");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWorkoutExercise", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.ExerciseDefinition", "ExerciseDefinition")
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trAInr.Domain.Entities.ProgramTemplateWorkoutDay", "ProgramTemplateWorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("ProgramTemplateWorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDefinition");

                    b.Navigation("ProgramTemplateWorkoutDay");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.AssignedProgram", "AssignedProgram")
                        .WithMany("Weeks")
                        .HasForeignKey("AssignedProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedProgram");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.HasOne("trAInr.Domain.Entities.ProgrammeWeek", "ProgrammeWeek")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("ProgrammeWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgrammeWeek");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.HasOne("trAInr.Domain.Aggregates.ExerciseDefinition", "ExerciseDefinition")
                        .WithMany()
                        .HasForeignKey("ExerciseDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trAInr.Domain.Entities.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseDefinition");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.AssignedProgram", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("trAInr.Domain.Aggregates.ProgramTemplate", b =>
                {
                    b.Navigation("Weeks");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWeek", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgramTemplateWorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.ProgrammeWeek", b =>
                {
                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("trAInr.Domain.Entities.WorkoutExercise", b =>
                {
                    b.Navigation("Sets");
                });
#pragma warning restore 612, 618
        }
    }
}
